In [53]:
import pybamm

In [54]:
model = pybamm.lithium_ion.DFN()
sim = pybamm.Simulation(model)
sim.solve([0, 3600])

In [55]:
sim.plot()

interactive(children=(FloatSlider(value=0.0, description='t', max=1.0, step=0.01), Output()), _dom_classes=('w…

In [56]:
output_variables = ["Electrolyte concentration [mol.m-3]", "Voltage [V]"]
sim.plot(output_variables=output_variables)

interactive(children=(FloatSlider(value=0.0, description='t', max=1.0, step=0.01), Output()), _dom_classes=('w…

In [57]:
output_variables = ["Voltage [V]"]
sim.plot(output_variables=output_variables)

interactive(children=(FloatSlider(value=0.0, description='t', max=1.0, step=0.01), Output()), _dom_classes=('w…

In [58]:
sim.plot(
    [
        ["Electrode current density [A.m-2]", "Electrolyte current density [A.m-2]"],
        "Voltage [V]",
    ]
)

interactive(children=(FloatSlider(value=0.0, description='t', max=1.0, step=0.01), Output()), _dom_classes=('w…

In [59]:
model.variable_names()

['Time [s]',
 'Time [min]',
 'Time [h]',
 'x [m]',
 'x_n [m]',
 'x_s [m]',
 'x_p [m]',
 'r_n [m]',
 'r_p [m]',
 'Current variable [A]',
 'Total current density [A.m-2]',
 'Current [A]',
 'C-rate',
 'Discharge capacity [A.h]',
 'Throughput capacity [A.h]',
 'Discharge energy [W.h]',
 'Throughput energy [W.h]',
 'Porosity',
 'Negative electrode porosity',
 'X-averaged negative electrode porosity',
 'Separator porosity',
 'X-averaged separator porosity',
 'Positive electrode porosity',
 'X-averaged positive electrode porosity',
 'Porosity change',
 'Negative electrode porosity change [s-1]',
 'X-averaged negative electrode porosity change [s-1]',
 'Separator porosity change [s-1]',
 'X-averaged separator porosity change [s-1]',
 'Positive electrode porosity change [s-1]',
 'X-averaged positive electrode porosity change [s-1]',
 'Negative electrode interface utilisation variable',
 'X-averaged negative electrode interface utilisation variable',
 'Negative electrode interface utilisation',


In [60]:
model.variables.search("temperature ")

Ambient temperature [C]
Ambient temperature [K]
Cell temperature [C]
Cell temperature [K]
Negative current collector temperature [C]
Negative current collector temperature [K]
Negative electrode temperature [C]
Negative electrode temperature [K]
Positive current collector temperature [C]
Positive current collector temperature [K]
Positive electrode temperature [C]
Positive electrode temperature [K]
Separator temperature [C]
Separator temperature [K]
Volume-averaged ambient temperature [C]
Volume-averaged ambient temperature [K]
Volume-averaged cell temperature [C]
Volume-averaged cell temperature [K]
X-averaged cell temperature [C]
X-averaged cell temperature [K]
X-averaged negative electrode temperature [C]
X-averaged negative electrode temperature [K]
X-averaged positive electrode temperature [C]
X-averaged positive electrode temperature [K]
X-averaged separator temperature [C]
X-averaged separator temperature [K]


In [89]:
output_variables = ["Cell temperature [K]", "Voltage [V]"]
sim.plot(output_variables=output_variables)

interactive(children=(FloatSlider(value=0.0, description='t', max=1.0, step=0.01), Output()), _dom_classes=('w…

In [62]:
parameter_values = pybamm.ParameterValues("Chen2020")

In [63]:
parameter_values

{'Ambient temperature [K]': 298.15,
 'Boltzmann constant [J.K-1]': 1.380649e-23,
 'Bulk solvent concentration [mol.m-3]': 2636.0,
 'Cation transference number': 0.2594,
 'Cell cooling surface area [m2]': 0.00531,
 'Cell thermal expansion coefficient [m.K-1]': 1.1e-06,
 'Cell volume [m3]': 2.42e-05,
 'Contact resistance [Ohm]': 0,
 'Current function [A]': 5.0,
 'EC diffusivity [m2.s-1]': 2e-18,
 'EC initial concentration in electrolyte [mol.m-3]': 4541.0,
 'Electrode height [m]': 0.065,
 'Electrode width [m]': 1.58,
 'Electrolyte conductivity [S.m-1]': <function electrolyte_conductivity_Nyman2008 at 0x0000023141E2A290>,
 'Electrolyte diffusivity [m2.s-1]': <function electrolyte_diffusivity_Nyman2008 at 0x0000023141E2A200>,
 'Electron charge [C]': 1.602176634e-19,
 'Faraday constant [C.mol-1]': 96485.33212,
 'Ideal gas constant [J.K-1.mol-1]': 8.314462618,
 'Initial concentration in electrolyte [mol.m-3]': 1000.0,
 'Initial concentration in negative electrode [mol.m-3]': 29866.0,
 'Initi

In [64]:
model.print_parameter_info()

| Parameter                                                 | Type of parameter                                                                                                                                                                                           |
| ========================================================= | =========================================================================================================================================================================================================== |
| Upper voltage cut-off [V]                                 | Parameter                                                                                                                                                                                                   |
| Positive electrode Bruggeman coefficient (electrolyte)    | Parameter                                                                                                                             

In [65]:
parameter_values["Current function [A]"] = 10

In [66]:
sim = pybamm.Simulation(model, parameter_values=parameter_values)
sim.solve([0, 3600])
sim.plot()

interactive(children=(FloatSlider(value=0.0, description='t', max=1703.0718416496497, step=17.030718416496498)…

In [67]:
import numpy as np


def my_current(t):
    return pybamm.sin(2 * np.pi * t / 60)


parameter_values["Current function [A]"] = my_current

In [68]:
sim = pybamm.Simulation(model, parameter_values=parameter_values)
t_eval = np.arange(0, 121, 1)
sim.solve(t_eval=t_eval)
sim.plot(["Current [A]", "Voltage [V]"])

interactive(children=(FloatSlider(value=0.0, description='t', max=120.0, step=1.2), Output()), _dom_classes=('…

In [69]:
def cube(t):
    return t**3


parameter_values = pybamm.ParameterValues(
    {
        "Negative electrode thickness [m]": 1e-4,
        "Positive electrode thickness [m]": 1.2e-4,
        "Current function [A]": cube,
    }
)

In [71]:
experiment = pybamm.Experiment(
    [
        "Discharge at C/10 for 10 hours or until 3.3 V",
        "Rest for 1 hour",
        "Charge at 1 A until 4.1 V",
        "Hold at 4.1 V until 50 mA",
        "Rest for 1 hour",
    ]
)

In [72]:
experiment = pybamm.Experiment(
    [
        (
            "Discharge at C/10 for 10 hours or until 3.3 V",
            "Rest for 1 hour",
            "Charge at 1 A until 4.1 V",
            "Hold at 4.1 V until 50 mA",
            "Rest for 1 hour",
        )
    ]
    * 3
    + [
        "Discharge at 1C until 3.3 V",
    ]
)

In [73]:
model = pybamm.lithium_ion.DFN()
sim = pybamm.Simulation(model, experiment=experiment)

In [74]:
sim.solve()

At t = 522.66, , mxstep steps taken before reaching tout.


In [75]:
sim.plot()

interactive(children=(FloatSlider(value=0.0, description='t', max=40.13294901709057, step=0.4013294901709057),…

In [76]:
sim.solution.cycles[0].plot()

interactive(children=(FloatSlider(value=0.0, description='t', max=13.076977039958468, step=0.13076977039958468…

In [77]:
pybamm.step.string(
    "Discharge at 1C for 1 hour", period="1 minute", temperature="25oC", tags=["tag1"]
)

_Step(C-rate, 1.0, duration=1 hour, period=1 minute, temperature=25oC, tags=['tag1'], description=Discharge at 1C for 1 hour)

In [78]:
pybamm.step.current(1, duration="1 hour", termination="2.5 V")

_Step(current, 1, duration=1 hour, termination=2.5 V)

In [79]:
pybamm.step.string("Discharge at 1A for 1 hour or until 2.5V")

_Step(current, 1.0, duration=1 hour, termination=2.5V, description=Discharge at 1A for 1 hour or until 2.5V)

In [80]:
t = np.linspace(0, 1, 60)
sin_t = 0.5 * np.sin(2 * np.pi * t)
drive_cycle_power = np.column_stack([t, sin_t])
experiment = pybamm.Experiment([pybamm.step.power(drive_cycle_power)])
sim = pybamm.Simulation(model, experiment=experiment)
sim.solve()
sim.plot()

interactive(children=(FloatSlider(value=0.0, description='t', max=1.0, step=0.01), Output()), _dom_classes=('w…

In [81]:
model = pybamm.lithium_ion.SPMe()
sim = pybamm.Simulation(model)
sim.solve([0, 3600])

In [17]:
experiment = pybamm.Experiment([
    "Charge at 1C until 4.1 V", 
    "Hold at 4.1V until 50 mA",
    "Discharge at 2 C until 3.105 V",
])

model = pybamm.lithium_ion.DFN()
sim = pybamm.Simulation(model, experiment=experiment)

2024-03-29 17:08:06.808 - [INFO] base_model._build_model(652): Start building Doyle-Fuller-Newman model
2024-03-29 17:08:06.872 - [INFO] base_battery_model.build_model(1073): Finish building Doyle-Fuller-Newman model


In [18]:
solution = sim.solution

In [19]:
solution = sim.solve([0, 7200])

2024-03-29 17:08:08.224 - [INFO] callbacks.on_experiment_start(164): Start running experiment
2024-03-29 17:08:08.225 - [INFO] parameter_values.process_model(394): Start setting parameters for Doyle-Fuller-Newman model
2024-03-29 17:08:08.344 - [INFO] parameter_values.process_model(463): Finish setting parameters for Doyle-Fuller-Newman model
2024-03-29 17:08:08.347 - [INFO] parameter_values.process_model(394): Start setting parameters for Doyle-Fuller-Newman model
2024-03-29 17:08:08.462 - [INFO] parameter_values.process_model(463): Finish setting parameters for Doyle-Fuller-Newman model
2024-03-29 17:08:08.464 - [INFO] parameter_values.process_model(394): Start setting parameters for Doyle-Fuller-Newman model
2024-03-29 17:08:08.583 - [INFO] parameter_values.process_model(463): Finish setting parameters for Doyle-Fuller-Newman model
2024-03-29 17:08:08.586 - [INFO] discretisation.process_model(145): Start discretising Doyle-Fuller-Newman model
2024-03-29 17:08:08.592 - [INFO] discret

In [20]:
t = solution["Time [s]"]
V = solution["Voltage [V]"]
temp = solution["X-averaged cell temperature [K]"]

In [21]:
V.entries

array([3.9320317 , 3.95075231, 3.96015467, 3.96865847, 3.97744769,
       3.98778662, 4.00246052, 4.02537822, 4.05464828, 4.08477975,
       4.09999   , 4.1       , 4.1       , 4.1       , 4.1       ,
       4.1       , 4.1       , 4.1       , 4.1       , 4.1       ,
       4.1       , 4.1       , 4.1       , 4.1       , 4.1       ,
       4.1       , 4.1       , 4.1       , 4.1       , 3.9590882 ,
       3.80434853, 3.75930585, 3.74393981, 3.73244703, 3.7201707 ,
       3.70681093, 3.69297646, 3.67919554, 3.66571107, 3.65285375,
       3.64086759, 3.62983947, 3.61975631, 3.61054891, 3.60211285,
       3.59432913, 3.58706301, 3.58014568, 3.57326274, 3.56575303,
       3.55860544, 3.55304147, 3.54870693, 3.54473636, 3.54064546,
       3.53635599, 3.53179183, 3.52676158, 3.52086564, 3.51358693,
       3.50447627, 3.49284198, 3.47664389, 3.45188747, 3.4058855 ,
       3.26758029, 3.10501   ])

In [23]:
temp.entries

array([298.15, 298.15, 298.15, 298.15, 298.15, 298.15, 298.15, 298.15,
       298.15, 298.15, 298.15, 298.15, 298.15, 298.15, 298.15, 298.15,
       298.15, 298.15, 298.15, 298.15, 298.15, 298.15, 298.15, 298.15,
       298.15, 298.15, 298.15, 298.15, 298.15, 298.15, 298.15, 298.15,
       298.15, 298.15, 298.15, 298.15, 298.15, 298.15, 298.15, 298.15,
       298.15, 298.15, 298.15, 298.15, 298.15, 298.15, 298.15, 298.15,
       298.15, 298.15, 298.15, 298.15, 298.15, 298.15, 298.15, 298.15,
       298.15, 298.15, 298.15, 298.15, 298.15, 298.15, 298.15, 298.15,
       298.15, 298.15, 298.15])

In [24]:
t.entries

array([   0.        ,   60.        ,  120.        ,  180.        ,
        240.        ,  300.        ,  360.        ,  420.        ,
        480.        ,  540.        ,  569.95278491,  569.95278491,
        629.95278491,  689.95278491,  749.95278491,  809.95278491,
        869.95278491,  929.95278491,  989.95278491, 1049.95278491,
       1109.95278491, 1169.95278491, 1229.95278491, 1289.95278491,
       1349.95278491, 1409.95278491, 1469.95278491, 1529.95278491,
       1577.87098408, 1577.87098408, 1637.87098408, 1697.87098408,
       1757.87098408, 1817.87098408, 1877.87098408, 1937.87098408,
       1997.87098408, 2057.87098408, 2117.87098408, 2177.87098408,
       2237.87098408, 2297.87098408, 2357.87098408, 2417.87098408,
       2477.87098408, 2537.87098408, 2597.87098408, 2657.87098408,
       2717.87098408, 2777.87098408, 2837.87098408, 2897.87098408,
       2957.87098408, 3017.87098408, 3077.87098408, 3137.87098408,
       3197.87098408, 3257.87098408, 3317.87098408, 3377.87098

In [88]:
V([200, 400, 780, 1236])  # times in seconds

array([3.729495  , 3.70861698, 3.67812431, 3.65402263])

In [1]:
#
# Compares the full and lumped thermal models for a single layer Li-ion cell
#
import pybamm

pybamm.set_logging_level("INFO")

# load models
# for the full model we use the "x-full" thermal submodel, which means that we solve
# the thermal model in the x-direction for a single-layer pouch cell
# for the lumped model we use the "arbitrary" cell geometry, which means that we can
# specify the surface area for cooling and total heat transfer coefficient
full_thermal_model = pybamm.lithium_ion.SPMe(
    {"thermal": "x-full"}, name="full thermal model"
)
lumped_thermal_model = pybamm.lithium_ion.SPMe(
    {"cell geometry": "arbitrary", "thermal": "lumped"}, name="lumped thermal model"
)
models = [full_thermal_model, lumped_thermal_model]

# load parameter values, we will use the Marquis2019 parameter set
parameter_values = pybamm.ParameterValues("Marquis2019")
# for the "full" model we use a heat transfer coefficient of 5 W.m-2.K-1 on the large
# surfaces of the pouch and zero heat transfer coefficient on the tabs and edges
full_params = parameter_values.copy()
full_params.update(
    {
        "Negative current collector surface heat transfer coefficient [W.m-2.K-1]"
        "": 5,
        "Positive current collector surface heat transfer coefficient [W.m-2.K-1]"
        "": 5,
        "Negative tab heat transfer coefficient [W.m-2.K-1]": 0,
        "Positive tab heat transfer coefficient [W.m-2.K-1]": 0,
        "Edge heat transfer coefficient [W.m-2.K-1]": 0,
    }
)
# for the lumped model we set the "Total heat transfer coefficient [W.m-2.K-1]"
# parameter as well as the "Cell cooling surface area [m2]" and "Cell volume [m3]
# parameters. Since the "full" model only accounts for cooling from the large surfaces
# of the pouch, we set the "Surface area for cooling [m2]" parameter to the area of the
# large surfaces of the pouch, and the total heat transfer coefficient to 5 W.m-2.K-1
A = parameter_values["Electrode width [m]"] * parameter_values["Electrode height [m]"]
contributing_layers = [
    "Negative current collector",
    "Negative electrode",
    "Separator",
    "Positive electrode",
    "Positive current collector",
]
total_thickness = sum(
    [parameter_values[layer + " thickness [m]"] for layer in contributing_layers]
)
electrode_volume = (
    total_thickness
    * parameter_values["Electrode height [m]"]
    * parameter_values["Electrode width [m]"]
)
lumped_params = parameter_values.copy()
lumped_params.update(
    {
        "Total heat transfer coefficient [W.m-2.K-1]": 5,
        "Cell cooling surface area [m2]": 2 * A,
        "Cell volume [m3]": electrode_volume,
    }
)

# loop over the models and solve
params = [full_params, lumped_params]
sols = []
for model, param in zip(models, params):
    sim = pybamm.Simulation(model, parameter_values=param)
    sim.solve([0, 3600])
    sols.append(sim.solution)

# plot
output_variables = [
    "Voltage [V]",
    "X-averaged cell temperature [K]",
    "Cell temperature [K]",
]
pybamm.dynamic_plot(sols, output_variables)

2024-03-29 17:04:33.468 - [INFO] base_model._build_model(652): Start building full thermal model
2024-03-29 17:04:33.587 - [INFO] base_battery_model.build_model(1073): Finish building full thermal model
2024-03-29 17:04:33.605 - [INFO] base_model._build_model(652): Start building lumped thermal model
2024-03-29 17:04:33.686 - [INFO] base_battery_model.build_model(1073): Finish building lumped thermal model
2024-03-29 17:04:33.698 - [INFO] parameter_values.process_model(394): Start setting parameters for full thermal model
2024-03-29 17:04:33.867 - [INFO] parameter_values.process_model(463): Finish setting parameters for full thermal model
2024-03-29 17:04:33.870 - [INFO] discretisation.process_model(145): Start discretising full thermal model
2024-03-29 17:04:33.886 - [INFO] discretisation.remove_independent_variables_from_rhs(1126): removing variable Discharge capacity [A.h] from rhs
2024-03-29 17:04:33.888 - [INFO] discretisation.remove_independent_variables_from_rhs(1126): removing 

interactive(children=(FloatSlider(value=0.0, description='t', max=1.0, step=0.01), Output()), _dom_classes=('w…

In [15]:
temp = sols[0]["Cell temperature [K]"]

In [16]:
temp.entries

array([[298.15      , 298.26145738, 298.31810723, ..., 298.57139159,
        298.63532892, 298.72181266],
       [298.15      , 298.26145957, 298.31810997, ..., 298.57139817,
        298.63533657, 298.72182176],
       [298.15      , 298.26146178, 298.31811272, ..., 298.57140477,
        298.63534427, 298.72183091],
       ...,
       [298.15      , 298.26161411, 298.31827602, ..., 298.57188143,
        298.63591236, 298.72252012],
       [298.15      , 298.26161263, 298.31827405, ..., 298.57187673,
        298.63590692, 298.72251368],
       [298.15      , 298.26161099, 298.31827189, ..., 298.5718715 ,
        298.63590084, 298.72250646]])